#!/usr/bin/env ruby

# This script handles the Travis build execution in the 'install' phase.
# It runs Bundler.

require 'pathname'
require 'fileutils'

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

system('bundle check --gemfile=Gemfile') || system!('bundle install --jobs=3 --retry=3 --gemfile=Gemfile')
