#!/usr/bin/env ruby

# This script handles the Travis build execution in the 'install' phase.
# It runs Bundler.

require 'pathname'
require 'fileutils'

project_root = Pathname.new File.expand_path('../../', __dir__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

FileUtils.chdir(project_root) do
  gemfile = "#{project_root}/Gemfile"
  system("bundle check --gemfile=#{gemfile}") || system!("bundle install --jobs=3 --retry=3 --gemfile=#{gemfile}")
end
